---
- name: install nginx
  apt:
    name: nginx
    state: present
- name: Copy nginx configuration for wordpress
  template: src=default.j2 dest=/etc/nginx/conf.d/default.conf
- name: copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: copy gzip config
  copy:
    src: gzip.conf
    dest: /etc/nginx/gzip.conf
- name: copy mime types
  copy: 
    src: mime.types
    dest: /etc/nginx/mime.types
- name: remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

