---
- name: install php stuff
  apt:
    name: "{{packages}}"
#- name: Disable default pool
#  become: yes
#  become_user: root
#  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled creates=/etc/php/7.0/fpm/pool.d/www.disabled
#  notify: restart php-fpm
- name: copy php-fpm config
  template: src=wordpress.j2 dest=/etc/php/7.0/fpm/wordpress.conf
  notify: restart php-fpm
